#!/usr/bin/env python3
"""
build_index.py
==============
(Re)build index.html as the interactive DIRECTORY TABLE.

The table renders client-side from data/directory.json (regenerated by
build_directory.py from the live outreach_state.json), so status / tier /
last-contacted are always current. This script just (re)writes the static
shell: header, controls, table markup, CSS, and the render/sort/filter JS.

It preserves the existing "Recent Updates" changelog block by extracting it
from the current index.html, so re-running is safe.

Usage:
    python3 data/build_directory.py     # refresh the data
    python3 data/build_index.py         # rebuild the shell (rarely needed)
"""
from __future__ import annotations
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INDEX = REPO / "index.html"


def extract_recent_updates(src: str) -> str:
    m = re.search(r'<details class="recent-updates">.*?</details>', src, re.DOTALL)
    return m.group(0) if m else (
        '<details class="recent-updates"><summary>&#9670; Recent Updates</summary>'
        '<ul></ul></details>'
    )


RECENT_PLACEHOLDER = "<!-- RECENT_UPDATES -->"

TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Out of Distribution People &mdash; Directory</title>
  <link rel="stylesheet" href="style.css">
  <style>
    body.dir-body { max-width: 1180px; }
    /* sticky header */
    .dir-top { position: sticky; top: 0; z-index: 50; background: var(--bg);
      border-bottom: 1px solid var(--border); margin: 0 -2rem 1.25rem; padding: 0.7rem 2rem 0.7rem; }
    .dir-top-row { display: flex; align-items: baseline; justify-content: space-between; gap: 1rem; flex-wrap: wrap; }
    .dir-title { font-family: var(--mono); font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.12em; color: var(--fg-muted); }
    .dir-top-links { display: flex; gap: 1.1rem; font-family: var(--mono); font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.08em; }
    .dir-top-links a { color: var(--fg-muted); text-decoration: none; padding-bottom: 0.15rem; border-bottom: 1px solid transparent; }
    .dir-top-links a:hover, .dir-top-links a.cur { color: var(--accent); border-bottom-color: var(--accent); }
    /* controls */
    .dir-search { width: 100%; box-sizing: border-box; padding: 0.6rem 0.8rem; font-size: 0.95rem;
      font-family: var(--mono); border: 1px solid var(--border); border-radius: 4px; background: #fff; color: var(--fg); margin-bottom: 0.6rem; }
    .dir-search:focus { outline: none; border-color: var(--accent); }
    .dir-filters { display: flex; flex-wrap: wrap; gap: 0.35rem 0.4rem; align-items: center; margin-bottom: 0.5rem; }
    .pill { font-family: var(--mono); font-size: 0.66rem; text-transform: uppercase; letter-spacing: 0.04em;
      padding: 0.2rem 0.5rem; border: 1px solid var(--border); border-radius: 999px; background: #fff; color: var(--fg-muted); cursor: pointer; user-select: none; }
    .pill:hover { border-color: var(--accent); color: var(--accent); }
    .pill.active { background: var(--fg); color: #fff; border-color: var(--fg); }
    .pill.active.tier-T0 { background: #c43d2e; border-color: #c43d2e; }
    .pill.active.tier-T1 { background: #d98324; border-color: #d98324; }
    .pill.active.tier-T2 { background: #6b7280; border-color: #6b7280; }
    .pill-sep { width: 1px; height: 16px; background: var(--border); margin: 0 0.3rem; }
    .pill-label { font-family: var(--mono); font-size: 0.6rem; text-transform: uppercase; letter-spacing: 0.1em; color: var(--fg-faint); margin-right: 0.1rem; }
    .dir-meta { font-family: var(--mono); font-size: 0.72rem; color: var(--fg-faint); margin: 0.2rem 0 0.8rem; }
    /* table */
    table.dir-table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
    .dir-table thead th { position: sticky; top: 96px; background: var(--bg); z-index: 5;
      text-align: left; font-family: var(--mono); font-size: 0.62rem; text-transform: uppercase; letter-spacing: 0.08em;
      color: var(--fg-faint); font-weight: 600; padding: 0.4rem 0.6rem; border-bottom: 1px solid var(--border); cursor: pointer; white-space: nowrap; }
    .dir-table thead th.nosort { cursor: default; }
    .dir-table thead th .arr { color: var(--accent); }
    .dir-table tbody tr { border-bottom: 1px solid var(--border-light); cursor: pointer; }
    .dir-table tbody tr:hover { background: #f2f1ec; }
    .dir-table td { padding: 0.5rem 0.6rem; vertical-align: top; }
    .c-tier { width: 38px; }
    .t-chip { display: inline-block; font-family: var(--mono); font-size: 0.6rem; font-weight: 700; letter-spacing: 0.04em;
      color: #fff; padding: 0.12rem 0.34rem; border-radius: 2px; }
    .t-chip.t0 { background: #c43d2e; } .t-chip.t1 { background: #d98324; }
    .t-chip.t2 { background: #6b7280; } .t-chip.t3 { background: #b8b8b0; }
    .t-chip.tnone { background: #d8d8d2; color: #777; }
    .c-person { min-width: 230px; }
    .p-name { font-weight: 600; color: var(--fg); }
    .p-name .indian-dot { color: var(--accent); font-size: 0.7rem; }
    .p-role { color: var(--fg-muted); font-size: 0.78rem; margin-top: 0.1rem;
      display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; max-width: 340px; }
    .sig { display: inline-block; font-family: var(--mono); font-size: 0.56rem; text-transform: uppercase; letter-spacing: 0.04em;
      padding: 0.05rem 0.3rem; border-radius: 2px; margin: 0.18rem 0.2rem 0 0; }
    .sig-stealth { background: #fbeae0; color: #b4571f; } .sig-departed { background: #fde8e6; color: #c43d2e; }
    .sig-raising { background: #e6f0e9; color: #2f6f4f; } .sig-founder { background: #ece4f5; color: #5b4b8a; }
    .sig-cluster { background: #eef0f2; color: #555; }
    .c-why { color: var(--fg-muted); font-size: 0.78rem; max-width: 360px; }
    .c-why .why-txt { display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
    .c-status { white-space: nowrap; font-size: 0.76rem; }
    .dot { display: inline-block; width: 7px; height: 7px; border-radius: 50%; margin-right: 0.35rem; vertical-align: middle; }
    .dot-not-contacted { background: #cfcfc8; } .dot-contacted { background: #d98324; }
    .dot-replied { background: #2f6f4f; } .dot-meeting { background: #2f6f4f; } .dot-passed { background: #cf6f6f; }
    .c-status .sub { color: var(--fg-faint); font-size: 0.68rem; font-family: var(--mono); margin-top: 0.12rem; }
    .c-upd { white-space: nowrap; font-family: var(--mono); font-size: 0.72rem; color: var(--fg-faint); }
    .c-act { white-space: nowrap; text-align: right; }
    .act { display: inline-block; font-family: var(--mono); font-size: 0.66rem; text-decoration: none; border: 1px solid var(--border);
      border-radius: 3px; padding: 0.12rem 0.34rem; margin-left: 0.2rem; color: var(--fg-muted); }
    .act:hover { border-color: var(--accent); color: var(--accent); }
    .urgency-flag { color: var(--accent); font-weight: 700; margin-left: 0.25rem; }
    .dir-empty { padding: 2rem; text-align: center; color: var(--fg-faint); font-style: italic; }
    /* hide heavier columns on narrow screens */
    @media (max-width: 820px) {
      .c-why, .c-upd { display: none; }
      .dir-table thead th.h-why, .dir-table thead th.h-upd { display: none; }
    }
    @media (max-width: 600px) {
      .dir-top { margin: 0 -1rem 1rem; padding: 0.6rem 1rem; }
      .c-status { display: none; } .dir-table thead th.h-status { display: none; }
    }
    .recent-updates { margin-top: 2.5rem; }
  </style>
</head>
<body class="dir-body">

  <div class="dir-top">
    <div class="dir-top-row">
      <span class="dir-title">Out of Distribution People</span>
      <span class="dir-top-links">
        <a href="index.html" class="cur">Directory</a>
        <a href="queue.html">Outreach Queue &rarr;</a>
        <a href="delta-fellows.html">Delta Fellows</a>
      </span>
    </div>
  </div>

  <h1 style="margin-bottom:0.2rem;">People Repository</h1>
  <p class="subtitle" style="margin-top:0;">A searchable directory of exceptional builders, researchers, and outliers &mdash; click any row to open the dossier.</p>

  <input type="text" id="dir-search" class="dir-search" placeholder="Search name, role, company, tag, cluster&hellip;" autocomplete="off" />

  <div class="dir-filters" id="tier-filters"><span class="pill-label">Tier</span></div>
  <div class="dir-filters" id="signal-filters"><span class="pill-label">Signal</span></div>
  <div class="dir-filters" id="meta-filters"><span class="pill-label">Status</span></div>

  <div class="dir-meta" id="dir-meta">loading&hellip;</div>

  <table class="dir-table">
    <thead>
      <tr>
        <th class="c-tier" data-sort="tier">Tier <span class="arr"></span></th>
        <th class="c-person" data-sort="name">Person <span class="arr"></span></th>
        <th class="h-why nosort">Why</th>
        <th class="h-status" data-sort="status">Status <span class="arr"></span></th>
        <th class="h-upd" data-sort="updated">Updated <span class="arr"></span></th>
        <th class="nosort">Reach</th>
      </tr>
    </thead>
    <tbody id="dir-body"></tbody>
  </table>
  <div class="dir-empty" id="dir-empty" style="display:none;">No one matches those filters.</div>

  <!-- RECENT_UPDATES -->

  <footer style="margin-top:2.5rem;">
    <span id="dir-foot">&mdash;</span> &middot; data regenerated by the morning ritual &middot;
    <a href="queue.html">outreach queue</a> &middot; <a href="delta-fellows.html">144 Delta fellows</a>
  </footer>

  <script>
  (function () {
    var TIERS = [['T0','0'],['T1','1'],['T2','2'],['T3','3'],['—','none']];
    var SIGNALS = ['stealth','departed','raising','founder'];
    var STATUSES = ['not-contacted','contacted','replied','meeting','passed'];
    var state = { q:'', tier:'all', signals:{}, status:'all', indian:false, urgency:false, delta:'all',
                  sortKey:'tier', sortDir:1 };
    var DATA = [], body = document.getElementById('dir-body'),
        meta = document.getElementById('dir-meta'), empty = document.getElementById('dir-empty');

    function esc(s){ return (s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
    function tierChip(t){
      if (t===null||t===undefined) return '<span class="t-chip tnone">—</span>';
      return '<span class="t-chip t'+t+'">T'+t+'</span>';
    }
    function tierRank(t){ return (t===null||t===undefined)?9:t; }

    function matches(p){
      if (state.tier!=='all'){ var tv = (p.tier===null||p.tier===undefined)?'none':String(p.tier); if (tv!==state.tier) return false; }
      var act = Object.keys(state.signals).filter(function(k){return state.signals[k];});
      if (act.length && !act.every(function(s){return (p.signals||[]).indexOf(s)>=0;})) return false;
      if (state.status!=='all' && p.status!==state.status) return false;
      if (state.indian && !p.indian) return false;
      if (state.delta==='only' && !p.delta) return false;
      if (state.delta==='hide' && p.delta) return false;
      if (state.urgency && !p.urgency) return false;
      if (state.q){
        var hay = (p.name+' '+p.role+' '+p.spike+' '+(p.tags||[]).join(' ')+' '+(p.cluster||'')+' '+(p.signals||[]).join(' ')).toLowerCase();
        if (hay.indexOf(state.q)<0) return false;
      }
      return true;
    }

    function sortRows(rows){
      var k = state.sortKey, d = state.sortDir;
      rows.sort(function(a,b){
        var av, bv;
        if (k==='tier'){ av=tierRank(a.tier); bv=tierRank(b.tier);
          if (av!==bv) return (av-bv)*d;
          return (b.updated||'').localeCompare(a.updated||''); }
        if (k==='name'){ return a.name.localeCompare(b.name)*d; }
        if (k==='status'){ av=STATUSES.indexOf(a.status); bv=STATUSES.indexOf(b.status); return (av-bv)*d; }
        if (k==='updated'){ return (a.updated||'').localeCompare(b.updated||'')*d*-1; }
        return 0;
      });
      return rows;
    }

    function rowHTML(p){
      var sigs = (p.signals||[]).map(function(s){return '<span class="sig sig-'+s+'">'+s+'</span>';}).join('');
      if (p.cluster) sigs += '<span class="sig sig-cluster">'+esc(p.cluster)+'</span>';
      var acts = '';
      if (p.twitter) acts += '<a class="act" href="https://twitter.com/'+encodeURIComponent(p.twitter)+'" target="_blank" rel="noopener" data-stop title="@'+esc(p.twitter)+'">𝕏</a>';
      if (p.linkedin) acts += '<a class="act" href="https://linkedin.com/in/'+encodeURIComponent(p.linkedin)+'" target="_blank" rel="noopener" data-stop title="LinkedIn">in</a>';
      if (p.gmail_url) acts += '<a class="act" href="'+esc(p.gmail_url)+'" target="_blank" rel="noopener" data-stop title="'+esc(p.email||'email')+'">✉</a>';
      else if (p.email) acts += '<a class="act" href="mailto:'+esc(p.email)+'" data-stop title="'+esc(p.email)+'">✉</a>';
      var sub = p.last_contacted ? ('contacted '+p.last_contacted) : (p.next_action_date ? ('by '+p.next_action_date) : '');
      return ''+
        '<td class="c-tier">'+tierChip(p.tier)+(p.urgency?'<span class="urgency-flag" title="urgency set">!</span>':'')+'</td>'+
        '<td class="c-person"><div class="p-name">'+esc(p.name)+(p.indian?' <span class="indian-dot" title="Indian / Indian-origin">●</span>':'')+'</div>'+
          (p.role?'<div class="p-role">'+esc(p.role)+'</div>':'')+
          (sigs?'<div>'+sigs+'</div>':'')+'</td>'+
        '<td class="c-why h-why"><div class="why-txt">'+esc(p.spike)+'</div></td>'+
        '<td class="c-status h-status"><span class="dot dot-'+p.status+'"></span>'+p.status+(sub?'<div class="sub">'+esc(sub)+'</div>':'')+'</td>'+
        '<td class="c-upd h-upd">'+(p.updated||'—')+'</td>'+
        '<td class="c-act">'+acts+'</td>';
    }

    function render(){
      var rows = DATA.filter(matches);
      sortRows(rows);
      body.innerHTML = '';
      empty.style.display = rows.length ? 'none' : 'block';
      var frag = document.createDocumentFragment();
      rows.forEach(function(p){
        var tr = document.createElement('tr');
        tr.className = 'dir-row';
        tr.innerHTML = rowHTML(p);
        tr.addEventListener('click', function(ev){
          if (ev.target.closest('[data-stop]')) return;   // let action links work
          window.location.href = 'people/'+p.slug+'.html';
        });
        frag.appendChild(tr);
      });
      body.appendChild(frag);
      meta.textContent = rows.length + ' of ' + DATA.length + ' people' +
        (state.q||state.tier!=='all'||state.status!=='all'||state.indian||state.urgency||state.delta!=='all'||Object.values(state.signals).some(Boolean) ? '  (filtered)' : '');
      // header arrows
      document.querySelectorAll('.dir-table th[data-sort]').forEach(function(th){
        var a = th.querySelector('.arr');
        if (th.dataset.sort===state.sortKey) a.textContent = state.sortDir>0?'▲':'▼'; else a.textContent='';
      });
    }

    function buildFilters(){
      var tf = document.getElementById('tier-filters');
      var present = {}; DATA.forEach(function(p){ present[(p.tier===null||p.tier===undefined)?'none':String(p.tier)]=true; });
      var allP = mkPill('All', state.tier==='all', function(){ state.tier='all'; syncTier(); render(); });
      tf.appendChild(allP);
      TIERS.forEach(function(t){
        if (!present[t[1]]) return;
        var n = DATA.filter(function(p){return ((p.tier===null||p.tier===undefined)?'none':String(p.tier))===t[1];}).length;
        var pill = mkPill(t[0]+' ('+n+')', state.tier===t[1], function(){ state.tier=t[1]; syncTier(); render(); });
        if (t[1]!=='none') pill.classList.add('tier-T'+t[1]);
        pill.dataset.tier=t[1];
        tf.appendChild(pill);
      });
      var sf = document.getElementById('signal-filters');
      SIGNALS.forEach(function(s){
        var n = DATA.filter(function(p){return (p.signals||[]).indexOf(s)>=0;}).length;
        if (!n) return;
        var pill = mkPill(s+' ('+n+')', false, function(){ state.signals[s]=!state.signals[s]; pill.classList.toggle('active'); render(); });
        pill.dataset.sig=s; sf.appendChild(pill);
      });
      var mf = document.getElementById('meta-filters');
      var allS = mkPill('All', true, function(){ state.status='all'; syncStatus(); render(); }); allS.dataset.st='all'; mf.appendChild(allS);
      STATUSES.forEach(function(s){
        var n = DATA.filter(function(p){return p.status===s;}).length; if (!n) return;
        var pill = mkPill(s+' ('+n+')', false, function(){ state.status=s; syncStatus(); render(); }); pill.dataset.st=s; mf.appendChild(pill);
      });
      mf.appendChild(sep());
      mf.appendChild(mkPill('★ urgency', false, function(){ state.urgency=!state.urgency; this.classList.toggle('active'); render(); }));
      mf.appendChild(mkPill('● indian', false, function(){ state.indian=!state.indian; this.classList.toggle('active'); render(); }));
      mf.appendChild(mkPill('hide delta', false, function(){ state.delta = state.delta==='hide'?'all':'hide'; this.classList.toggle('active'); render(); }));
    }
    function syncTier(){ document.querySelectorAll('#tier-filters .pill').forEach(function(p){
      var v = p.dataset.tier!==undefined?p.dataset.tier:'all'; p.classList.toggle('active', v===state.tier); }); }
    function syncStatus(){ document.querySelectorAll('#meta-filters .pill[data-st]').forEach(function(p){
      p.classList.toggle('active', p.dataset.st===state.status); }); }
    function mkPill(label, active, fn){ var b=document.createElement('span'); b.className='pill'+(active?' active':''); b.textContent=label; b.addEventListener('click', fn); return b; }
    function sep(){ var s=document.createElement('span'); s.className='pill-sep'; return s; }

    document.getElementById('dir-search').addEventListener('input', function(e){ state.q=e.target.value.toLowerCase().trim(); render(); });
    document.querySelectorAll('.dir-table th[data-sort]').forEach(function(th){
      th.addEventListener('click', function(){ var k=th.dataset.sort;
        if (state.sortKey===k) state.sortDir*=-1; else { state.sortKey=k; state.sortDir = (k==='name')?1:1; }
        render(); });
    });

    fetch('data/directory.json?t=' + Date.now()).then(function(r){return r.json();}).then(function(j){
      DATA = j.people || [];
      buildFilters(); render();
      document.getElementById('dir-foot').textContent = DATA.length + ' people indexed';
      var uc = document.getElementById('updates-count'); if (uc) uc.textContent = document.querySelectorAll('.recent-updates li').length;
    }).catch(function(err){
      meta.textContent = 'Could not load directory.json — run: python3 data/build_directory.py';
      console.error(err);
    });
  })();
  </script>
</body>
</html>
"""


def main():
    src = INDEX.read_text()
    recent = extract_recent_updates(src)
    out = TEMPLATE.replace(RECENT_PLACEHOLDER, recent)
    INDEX.write_text(out)
    print(f"index.html rebuilt as directory table ({len(out)} bytes); preserved Recent Updates block ({len(recent)} bytes).")


if __name__ == "__main__":
    main()
